#### Задание 1

In [1]:
import numpy as np

In [14]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11], 
              [3, 10],
              [1, 7]])

In [15]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [18]:
mean_a = a.mean(axis = 0)

In [19]:
mean_a

array([2. , 8.4])

#### Задание 2

In [31]:
a_centered = np.subtract(a, mean_a)

In [32]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### Задание 3 

In [33]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])

In [34]:
a_centered_sp

8.0

In [63]:
a_centered_sp / (a_centered[:, 0].size - 1)

2.0

#### Задание 4

In [64]:
m = a.T

In [65]:
m

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [67]:
np.cov(m)

array([[1. , 2. ],
       [2. , 4.3]])